add_newline = false

[nodejs]
symbol = "N.JS "

[python]
symbol = "PY "

[elm]
symbol = "Elm "

[java]
disabled = true

[package]
symbol = "PKG "

[cmd_duration]
disabled = true

[directory]
truncation_length = 5
truncate_to_repo = false
