add_newline = false

[nodejs]
symbol = "Node "

[python]
symbol = "Py "

[elm]
symbol = "Elm "

[package]
symbol = "PKG "

[cmd_duration]
disabled = true

[directory]
truncation_length = 5
truncate_to_repo = false
