[a-general]
home   = "gemini://geminispace.info"
search = "gemini://geminispace.info/search"
http           = "librewolf"
color          = true
ansi           = true
bullets        = true
auto_redirect  = true
emoji_favicons = true
left_margin    = 0.15
max_width      = 100
downloads      = ""
page_max_size  = 2097152
page_max_time  = 10
scrollbar      = "auto"


[keybindings]
bind_quit   = "q"
bind_bottom = ["i", ":", ";"]
bind_reload = ["Ctrl-R", "R"]
bind_save   = ["Ctrl-S", "W"]
bind_edit   = "I"

# Navigation
bind_back    = ["H", "h"]
bind_forward = ["L", "l"]

# Bookmaeks
bind_bookmarks    = "b"
bind_add_bookmark = "B"

# Tab
bind_new_tab   = "t"
bind_close_tab = "T"
bind_next_tab  = "J"
bind_prev_tab  = "K"

[theme]
bg             = "#262A2B"
fg             = "#dfdfdf"
tab_num        = "#797979"
bottombar_text = "#dfdfdf"
bottombar_bg   = "#1F2324"
scrollbar      = "#1F2324"
btn_bg         = "#1F2324"
btn_text       = "#dfdfdf"

[[mediatype-handlers]]
cmd       = "feh"
types     = "image"
no_prompt = true

[cache]
max_size  = 0
max_pages = 30
timeout   = 1800

[subscriptions]
popup            = true
workers          = 3
update_interval  = 1800
entries_per_page = 20

[auth]
[auth.certs]
[auth.keys]
[proxies]
